import ROLES from "./roles";
import PERMISSIONS from "./permissions";

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.CREATE_MEMBER,
    PERMISSIONS.EDIT_MEMBER,
    PERMISSIONS.VERIFY_MEMBER,
    PERMISSIONS.CHANGE_MEMBERSHIP_STATUS,

    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.DELETE_EVENT,

    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.MEMBER]: [],

  [ROLES.GUEST]: [],
};

export default ROLE_PERMISSIONS;